version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: 'jenkins'
    user: "${UID}:${GID}"
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:50000:50000"
    volumes:
      - '/usr/bin/docker:/usr/bin/docker'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './jenkins_home:/var/jenkins_home'
