version: '2.0'
services:
  wordpress:
    expose:
      - "80"
    image: 'wordpress:latest'
    container_name: 'wordpress'
    volumes:
      - './src/:/var/www/html/'
    restart: always
    networks:
      - databases
      - nginx-proxy
    environment:
      VIRTUAL_HOST: 'wordpress.example.com'
      WORDPRESS_DB_HOST: 'mysql:3306'
      WORDPRESS_DB_NAME: 'wordpress'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'password'
      WORDPRESS_TABLE_PREFIX: 'wp_'
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  databases:
    external:
      name: databases
  nginx-proxy:
    external:
      name: nginx-proxy
